spring:
  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/alquilerhardware
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  sql:
    init:
      mode: always
logging:
  pattern.console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org.hibernate.SQL: WARN
    root: warn
